/* Ridwaan Mobile Store — dependency-free mobile commerce demo */
const PRODUCTS = [
  {id:1,name:'iPhone 16 Pro Max',brand:'Apple',image:'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=700&q=85',price:1199,oldPrice:1399,discount:14,rating:4.9,reviews:824,storage:['256GB','512GB','1TB'],colors:[['Desert Titanium','#bba48f'],['Black Titanium','#292725'],['Natural Titanium','#c5bfb5']],stock:true,description:'A premium titanium smartphone with an immersive display, pro camera system and all-day battery life.',points:240},
  {id:2,name:'iPhone 15',brand:'Apple',image:'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=700&q=85',price:699,oldPrice:799,discount:13,rating:4.7,reviews:612,storage:['128GB','256GB','512GB'],colors:[['Pink','#e8c8ca'],['Blue','#c8d8dc'],['Black','#30302e']],stock:true,description:'A bright, dependable iPhone with a powerful camera, Dynamic Island and smooth everyday performance.',points:140},
  {id:3,name:'Samsung Galaxy S25 Ultra',brand:'Samsung',image:'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=700&q=85',price:1299,oldPrice:1499,discount:13,rating:4.9,reviews:733,storage:['256GB','512GB','1TB'],colors:[['Titanium Gray','#8e8a82'],['Titanium Black','#272727'],['Titanium Blue','#a9bac7']],stock:true,description:'Flagship Galaxy performance with an integrated S Pen, intelligent camera tools and a vivid edge-to-edge display.',points:260},
  {id:4,name:'Samsung Galaxy A56',brand:'Samsung',image:'https://images.unsplash.com/photo-1605236453806-6ff36851218e?auto=format&fit=crop&w=700&q=85',price:449,oldPrice:499,discount:10,rating:4.6,reviews:381,storage:['128GB','256GB'],colors:[['Awesome Graphite','#414141'],['Awesome Olive','#adb49c'],['Awesome Pink','#e6c6c4']],stock:true,description:'A refined mid-range Galaxy with a crisp AMOLED display, reliable cameras and impressive battery endurance.',points:90},
  {id:5,name:'Google Pixel 9 Pro',brand:'Google',image:'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=700&q=85',price:999,oldPrice:1099,discount:9,rating:4.8,reviews:426,storage:['128GB','256GB','512GB'],colors:[['Obsidian','#292928'],['Porcelain','#e5ded0'],['Hazel','#a6a798']],stock:true,description:'Google’s most polished phone with a brilliant camera, helpful on-device intelligence and seven years of updates.',points:200},
  {id:6,name:'Google Pixel 8a',brand:'Google',image:'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=700&q=85',price:449,oldPrice:549,discount:18,rating:4.6,reviews:297,storage:['128GB','256GB'],colors:[['Bay','#9ac5d5'],['Obsidian','#292929'],['Porcelain','#e5ddd1']],stock:false,description:'A compact Pixel experience with excellent photography, clean software and dependable everyday speed.',points:90},
  {id:7,name:'Xiaomi 15 Ultra',brand:'Xiaomi',image:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=700&q=85',price:1099,oldPrice:1249,discount:12,rating:4.8,reviews:344,storage:['256GB','512GB','1TB'],colors:[['Black','#222'],['White','#e8e5df'],['Silver Chrome','#bfc2c4']],stock:true,description:'A photography-first flagship with a large sensor camera, bold design and extremely fast charging.',points:220},
  {id:8,name:'Redmi Note 14 Pro',brand:'Xiaomi',image:'https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=700&q=85',price:379,oldPrice:449,discount:16,rating:4.5,reviews:518,storage:['128GB','256GB'],colors:[['Midnight Black','#292929'],['Lavender Purple','#b8a9c7'],['Coral Green','#8ca99d']],stock:true,description:'Exceptional value with a smooth display, detailed main camera and a battery made for busy days.',points:76},
  {id:9,name:'OnePlus 13',brand:'OnePlus',image:'https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=700&q=85',price:899,oldPrice:999,discount:10,rating:4.8,reviews:274,storage:['256GB','512GB'],colors:[['Black Eclipse','#292728'],['Arctic Dawn','#e6e4df'],['Midnight Ocean','#263b47']],stock:true,description:'Fast and fluid flagship performance, a premium camera system and rapid charging in an elegant body.',points:180},
  {id:10,name:'Nothing Phone 3',brand:'Nothing',image:'https://images.unsplash.com/photo-1603184017968-953f59cd2e37?auto=format&fit=crop&w=700&q=85',price:799,oldPrice:899,discount:11,rating:4.6,reviews:196,storage:['256GB','512GB'],colors:[['White','#e9e7e1'],['Black','#242424']],stock:true,description:'Distinct transparent-inspired design, expressive light interactions and a focused, delightfully clean interface.',points:160},
  {id:11,name:'Motorola Edge 60 Pro',brand:'Motorola',image:'https://images.unsplash.com/photo-1523206489230-c012c64b2b48?auto=format&fit=crop&w=700&q=85',price:649,oldPrice:749,discount:13,rating:4.5,reviews:163,storage:['256GB','512GB'],colors:[['Shadow','#34302e'],['Ocean Blue','#627f91'],['Dune','#c4aa8c']],stock:true,description:'A slim premium phone with a curved display, balanced cameras and clean software tuned for speed.',points:130},
  {id:12,name:'Honor Magic7 Pro',brand:'Honor',image:'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?auto=format&fit=crop&w=700&q=85',price:999,oldPrice:1199,discount:17,rating:4.7,reviews:221,storage:['256GB','512GB'],colors:[['Lunar Shadow','#57534f'],['Breeze Blue','#b5cad3'],['Black','#252525']],stock:true,description:'A sophisticated flagship with powerful portrait photography, a vibrant display and long-lasting performance.',points:200}
];

const DEFAULTS = {
  page:'home', cart:[], wishlist:[], points:1850, orders:[], theme:'light', notifications:true,
  biometric:true, language:'English', promo:'', usePoints:false,
  profile:{name:'Ridwaan',email:'ridwaan@example.com',phone:'',address:'',city:'Hargeisa'}
};
const state = {...DEFAULTS, ...readJSON('rms_state',{})};
state.profile = {...DEFAULTS.profile,...(state.profile||{})};
let shop = {query:'',brand:'All',maxPrice:1500,availability:'all',sort:'featured'};
let selected = null;
let detailChoice = {storage:'',color:'',qty:1};
let goldShown = false;
const app = document.getElementById('appView');
const nav = document.getElementById('bottomNav');
const modalRoot = document.getElementById('modalRoot');

const icon = (name, cls='') => `<svg class="${cls}" aria-hidden="true"><use href="#i-${name}"></use></svg>`;
const money = n => `$${Number(n).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const product = id => PRODUCTS.find(p=>p.id===Number(id));
function readJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function save(){localStorage.setItem('rms_state',JSON.stringify({...state,page:'home'}));document.body.classList.toggle('dark',state.theme==='dark');document.querySelector('meta[name="theme-color"]').content=state.theme==='dark'?'#171210':'#fbf5ef'}
function safe(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function init(){
  document.body.classList.toggle('dark',state.theme==='dark');
  updateClock(); setInterval(updateClock,30000);
  renderNav(); renderSkeleton();
  setTimeout(()=>setPage('home'),650);
  window.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet()});
}
function updateClock(){document.getElementById('clock').textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}).replace(/^0/,'')}
function renderSkeleton(){
  app.innerHTML=`<div class="greeting-row"><div><div class="skeleton" style="width:82px;height:10px;border-radius:5px"></div><div class="skeleton" style="width:150px;height:25px;border-radius:8px;margin-top:8px"></div></div><div class="skeleton" style="width:42px;height:42px;border-radius:50%"></div></div><div class="skeleton skeleton-hero"></div><div class="brand-strip">${Array(5).fill('<i class="skeleton" style="width:70px;height:35px;border-radius:20px;flex:0 0 auto"></i>').join('')}</div><div class="product-grid"><div class="skeleton skeleton-card"></div><div class="skeleton skeleton-card"></div></div>`;
}
function renderNav(){
  const tabs=[['home','Home'],['shop','Shop'],['cart','Cart'],['gift','Rewards'],['user','Profile']];
  const pageMap={gift:'rewards',user:'profile'};
  const count=state.cart.reduce((s,i)=>s+i.qty,0);
  nav.innerHTML=tabs.map(([ic,label])=>{const p=pageMap[ic]||ic;return `<button class="nav-item ${state.page===p?'active':''}" onclick="setPage('${p}')" aria-label="${label}">${icon(ic)}<span>${label}</span>${p==='cart'&&count?`<b class="nav-badge">${count}</b>`:''}</button>`}).join('');
}
function setPage(page){
  state.page=page; selected=null; app.className='app-view'; nav.hidden=false; renderNav();
  ({home:renderHome,shop:renderShop,cart:renderCart,rewards:renderRewards,profile:renderProfile}[page]||renderHome)();
  app.scrollTop=0; window.scrollTo({top:0,behavior:'smooth'});
}
function header(title,action=''){return `<header class="page-head"><div><p class="eyebrow">Ridwaan Mobile Store</p><h1>${title}</h1></div>${action||`<div class="page-head-spacer"></div>`}</header>`}
function imageMarkup(p,cls='product-media'){return `<div class="${cls}"><img src="${p.image}" alt="${safe(p.name)}" loading="lazy" onerror="imageFallback(this)"></div>`}
function imageFallback(img){img.parentElement.classList.add('fallback');img.removeAttribute('src')}
function stars(p){return `<span class="rating">${icon('star')} ${p.rating} <span>(${p.reviews})</span></span>`}
function productCard(p){
  const wished=state.wishlist.includes(p.id);
  return `<article class="product-card"><div class="product-media" onclick="showProduct(${p.id})" role="button" tabindex="0" onkeydown="if(event.key==='Enter')showProduct(${p.id})"><span class="discount-badge">-${p.discount}%</span><button class="wish-btn ${wished?'active':''}" onclick="event.stopPropagation();toggleWishlist(${p.id})" aria-label="${wished?'Remove from':'Add to'} wishlist">${icon('heart')}</button><img src="${p.image}" alt="${safe(p.name)}" loading="lazy" onerror="imageFallback(this)"></div><div class="product-info" onclick="showProduct(${p.id})"><span class="brand">${p.brand}</span><h3 class="product-name">${p.name}</h3>${stars(p)}<div class="price-row"><strong class="price">${money(p.price)}</strong><del class="old-price">${money(p.oldPrice)}</del><button class="add-btn" onclick="event.stopPropagation();quickAdd(${p.id})" aria-label="Add ${safe(p.name)} to cart">${icon('plus')}</button></div></div></article>`;
}

function renderHome(){
  app.innerHTML=`<header class="greeting-row"><div><p class="eyebrow">Welcome back</p><h1>Hello, ${safe(state.profile.name.split(' ')[0])} 👋</h1></div><div class="head-actions"><button class="icon-btn" onclick="showNotifications()" aria-label="Notifications">${icon('bell')}<i class="notification-dot"></i></button><button class="avatar" onclick="setPage('profile')" aria-label="Open profile">R</button></div></header>
  <div class="search-row"><label class="search-box">${icon('search')}<input id="homeSearch" placeholder="Search phones, brands..." aria-label="Search phones" onkeydown="homeSearchKey(event)"></label><button class="filter-btn" onclick="setPage('shop');setTimeout(openFilters,10)" aria-label="Open filters">${icon('sliders')}</button></div>
  <section class="hero"><div class="hero-copy"><span class="tag">New arrival</span><h2>Power meets premium.</h2><p>Meet the iPhone 16 Pro Max and earn 240 points.</p><button class="light-btn" onclick="showProduct(1)">Shop Now ${icon('arrow')}</button></div><div class="hero-phone"></div></section>
  <div class="brand-strip">${['All','Apple','Samsung','Google','Xiaomi','OnePlus'].map((b,i)=>`<button class="chip ${i===0?'active':''}" onclick="goBrand('${b}')">${b}</button>`).join('')}</div>
  <div class="section-head"><h2>Popular Phones</h2><button class="text-btn" onclick="setPage('shop')">See all</button></div><div class="h-scroll">${PRODUCTS.slice(0,6).map(productCard).join('')}</div>
  <div class="section-head"><h2>Special Offers</h2><button class="text-btn" onclick="goDeals()">View deals</button></div><div class="offer-row"><button class="offer-card" onclick="showProduct(3)"><span>Flagship deal</span><b>Save on Galaxy Ultra</b><i class="offer-icon">📱</i></button><button class="offer-card" onclick="goDeals()"><span>This week</span><b>Up to 18% off</b><i class="offer-icon">✨</i></button></div>
  <button class="rewards-mini" onclick="setPage('rewards')"><span class="coin">★</span><span><b>${state.points.toLocaleString()} Reward Points</b><p>Gold member · ${Math.max(0,3000-state.points).toLocaleString()} to Platinum</p></span><span class="icon-btn">${icon('chevron')}</span></button>`;
}
function homeSearchKey(e){if(e.key==='Enter'){shop.query=e.target.value.trim();setPage('shop')}}
function goBrand(brand){shop.brand=brand;setPage('shop')}
function goDeals(){shop.sort='discount';setPage('shop')}
function showNotifications(){openSheet(`<div class="sheet-head"><h2>Notifications</h2><button class="icon-btn close" onclick="closeSheet()" aria-label="Close">${icon('x')}</button></div><div class="activity-list"><div class="activity"><span class="activity-icon">🔥</span><span><b>Weekend offer is live</b><span>Save up to 18% on selected phones.</span></span></div><div class="activity"><span class="activity-icon">⭐</span><span><b>You’re a Gold member</b><span>Enjoy free delivery and 2× points.</span></span></div><div class="activity"><span class="activity-icon">📦</span><span><b>Fast delivery</b><span>Same-day delivery is available in Hargeisa.</span></span></div></div>`) }

function filteredProducts(){
  let list=PRODUCTS.filter(p=>(shop.brand==='All'||p.brand===shop.brand)&&(shop.availability==='all'||(shop.availability==='in'&&p.stock)||(shop.availability==='out'&&!p.stock))&&p.price<=shop.maxPrice&&(p.name+' '+p.brand).toLowerCase().includes(shop.query.toLowerCase()));
  if(shop.sort==='low')list.sort((a,b)=>a.price-b.price);if(shop.sort==='high')list.sort((a,b)=>b.price-a.price);if(shop.sort==='rating')list.sort((a,b)=>b.rating-a.rating);if(shop.sort==='discount')list.sort((a,b)=>b.discount-a.discount);
  return list;
}
function renderShop(){
  const list=filteredProducts();
  app.innerHTML=`${header('Shop',`<button class="icon-btn" onclick="openFilters()" aria-label="Filter products">${icon('sliders')}</button>`)}<div class="shop-tools"><label class="search-box">${icon('search')}<input value="${safe(shop.query)}" placeholder="Search product or brand" aria-label="Search products" oninput="shop.query=this.value;renderShop()"></label><div class="brand-strip">${['All','Apple','Samsung','Google','Xiaomi','OnePlus','Nothing','Motorola','Honor'].map(b=>`<button class="chip ${shop.brand===b?'active':''}" onclick="shop.brand='${b}';renderShop()">${b}</button>`).join('')}</div></div><div class="filter-summary"><span>${list.length} phone${list.length===1?'':'s'} found</span><label><span class="sr-only">Sort</span><select class="sort-select" onchange="shop.sort=this.value;renderShop()"><option value="featured" ${shop.sort==='featured'?'selected':''}>Featured</option><option value="low" ${shop.sort==='low'?'selected':''}>Price: Low to High</option><option value="high" ${shop.sort==='high'?'selected':''}>Price: High to Low</option><option value="rating" ${shop.sort==='rating'?'selected':''}>Top Rated</option><option value="discount" ${shop.sort==='discount'?'selected':''}>Biggest Discount</option></select></label></div>${list.length?`<div class="product-grid">${list.map(productCard).join('')}</div>`:`<div class="empty-state"><div class="empty-illustration">🔎</div><h2>No phones found</h2><p>Try changing your search or filters.</p><button class="primary-btn" onclick="clearFilters()">Clear Filters</button></div>`}`;
}
function openFilters(){
  openSheet(`<div class="sheet-head"><h2>Filter products</h2><button class="icon-btn close" onclick="closeSheet()" aria-label="Close filters">${icon('x')}</button></div><div class="filter-group"><label>Maximum price: <strong id="rangeValue">${money(shop.maxPrice)}</strong></label><div class="range-line"><span>$300</span><input id="priceRange" type="range" min="300" max="1500" step="50" value="${shop.maxPrice}" oninput="document.getElementById('rangeValue').textContent=money(this.value)"><span>$1,500</span></div></div><div class="filter-group"><label>Availability</label><div class="filter-checks"><button class="check-chip ${shop.availability==='all'?'active':''}" data-avail="all" onclick="sheetAvailability(this)">All</button><button class="check-chip ${shop.availability==='in'?'active':''}" data-avail="in" onclick="sheetAvailability(this)">In stock</button><button class="check-chip ${shop.availability==='out'?'active':''}" data-avail="out" onclick="sheetAvailability(this)">Out of stock</button></div></div><div class="filter-group"><label>Brand</label><div class="filter-checks">${['All','Apple','Samsung','Google','Xiaomi','OnePlus','Nothing','Motorola','Honor'].map(b=>`<button class="check-chip ${shop.brand===b?'active':''}" data-brand="${b}" onclick="sheetBrand(this)">${b}</button>`).join('')}</div></div><div class="sheet-actions"><button class="secondary-btn" onclick="clearFilters();closeSheet()">Clear</button><button class="primary-btn" onclick="applyFilters()">Show products</button></div>`);
}
function sheetAvailability(el){el.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));el.classList.add('active')}
function sheetBrand(el){el.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));el.classList.add('active')}
function applyFilters(){shop.maxPrice=Number(document.getElementById('priceRange').value);shop.availability=modalRoot.querySelector('[data-avail].active').dataset.avail;shop.brand=modalRoot.querySelector('[data-brand].active').dataset.brand;closeSheet();renderShop()}
function clearFilters(){shop={query:'',brand:'All',maxPrice:1500,availability:'all',sort:'featured'};if(state.page==='shop')renderShop()}

function showProduct(id){
  closeSheet();
  const p=product(id); selected=p;detailChoice={storage:p.storage[0],color:p.colors[0][0],qty:1};
  state.page='details';nav.hidden=true;app.className='app-view details-open';renderDetails();window.scrollTo(0,0);
}
function renderDetails(){
  const p=selected,wished=state.wishlist.includes(p.id);
  app.innerHTML=`<article class="details-page"><div class="detail-top"><button class="icon-btn" onclick="setPage('shop')" aria-label="Back to shop">${icon('back')}</button><button class="icon-btn wish-btn ${wished?'active':''}" onclick="toggleWishlist(${p.id});renderDetails()" aria-label="Toggle wishlist">${icon('heart')}</button></div><div class="detail-image"><img src="${p.image}" alt="${safe(p.name)}" onerror="imageFallback(this)"><span class="carousel-dots"><i class="active"></i><i></i><i></i></span></div><div class="detail-body"><span class="brand">${p.brand}</span><h1>${p.name}</h1><div class="detail-rating">${icon('star')} <strong>${p.rating}</strong> · ${p.reviews} verified reviews</div><div class="detail-price">${money(p.price)} <del>${money(p.oldPrice)}</del></div><p class="detail-desc">${p.description}</p><div class="option-block"><div class="option-label"><span>Choose color</span><span id="colorName">${detailChoice.color}</span></div><div class="choices">${p.colors.map(([n,c])=>`<button class="color-choice ${detailChoice.color===n?'active':''}" style="background:${c}" onclick="detailChoice.color='${n}';renderDetails()" aria-label="${n}" title="${n}"></button>`).join('')}</div></div><div class="option-block"><div class="option-label"><span>Storage</span><span>${detailChoice.storage}</span></div><div class="choices">${p.storage.map(s=>`<button class="storage-choice ${detailChoice.storage===s?'active':''}" onclick="detailChoice.storage='${s}';renderDetails()">${s}</button>`).join('')}</div></div><div class="stock-row"><span class="${p.stock?'stock':''}">${p.stock?'● In stock':'Out of stock'}</span><div class="qty-control"><button onclick="detailQty(-1)" aria-label="Decrease quantity">${icon('minus')}</button><b>${detailChoice.qty}</b><button onclick="detailQty(1)" aria-label="Increase quantity">${icon('plus')}</button></div></div><div class="rewards-mini"><span class="coin">★</span><span><b>Earn ${p.points*detailChoice.qty} points</b><p>Added after your order is completed</p></span></div></div></article><div class="sticky-add"><button class="primary-btn" ${p.stock?'':'disabled'} onclick="addDetailedToCart()">${icon('cart')} ${p.stock?'Add to Cart · '+money(p.price*detailChoice.qty):'Currently unavailable'}</button></div>`;
}
function detailQty(d){detailChoice.qty=Math.max(1,Math.min(9,detailChoice.qty+d));renderDetails()}
function addDetailedToCart(){addToCart(selected.id,detailChoice.storage,detailChoice.color,detailChoice.qty);toast(`${selected.name} added to cart`);setPage('cart')}
function quickAdd(id){const p=product(id);if(!p.stock)return toast('This phone is currently out of stock','!');addToCart(id,p.storage[0],p.colors[0][0],1);toast('Added to your cart')}
function addToCart(id,storage,color,qty){const key=`${id}-${storage}-${color}`;const found=state.cart.find(i=>i.key===key);found?found.qty+=qty:state.cart.push({key,id,storage,color,qty});save();renderNav();const badge=nav.querySelector('.nav-badge');if(badge)badge.classList.add('bump')}
function toggleWishlist(id){const i=state.wishlist.indexOf(id);i>=0?state.wishlist.splice(i,1):state.wishlist.push(id);save();toast(i>=0?'Removed from wishlist':'Saved to wishlist');if(state.page==='shop')renderShop();else if(state.page==='home')renderHome()}

function cartTotals(){
  const subtotal=state.cart.reduce((sum,i)=>sum+product(i.id).price*i.qty,0);const delivery=subtotal===0?0:subtotal>=900?0:15;const discount=state.promo==='RIDWAAN10'?subtotal*.1:0;const pointsDiscount=state.usePoints?Math.min(state.points/100,subtotal*.2):0;return {subtotal,delivery,discount,pointsDiscount,total:Math.max(0,subtotal+delivery-discount-pointsDiscount)};
}
function renderCart(){
  const t=cartTotals();
  app.innerHTML=`${header('My Cart')} ${state.cart.length?`<div class="cart-list">${state.cart.map(i=>{const p=product(i.id);return `<article class="cart-item"><div class="cart-thumb"><img src="${p.image}" alt="${safe(p.name)}" onerror="imageFallback(this)"></div><div><h3>${p.name}</h3><div class="cart-meta">${i.storage} · ${safe(i.color)}</div><strong class="price">${money(p.price*i.qty)}</strong><div class="mini-qty"><button onclick="cartQty('${i.key}',-1)" aria-label="Decrease">−</button><b>${i.qty}</b><button onclick="cartQty('${i.key}',1)" aria-label="Increase">+</button></div></div><button class="remove-btn" onclick="removeCart('${i.key}')" aria-label="Remove ${safe(p.name)}">${icon('trash')}</button></article>`}).join('')}</div><div class="promo-box"><input id="promo" value="${state.promo}" placeholder="Promo code (try RIDWAAN10)" aria-label="Promo code"><button onclick="applyPromo()">Apply</button></div><label class="reward-use"><input type="checkbox" ${state.usePoints?'checked':''} onchange="state.usePoints=this.checked;save();renderCart()"> Use reward points (save up to 20%)</label><div class="summary-card"><div class="summary-row"><span>Subtotal</span><strong>${money(t.subtotal)}</strong></div><div class="summary-row"><span>Delivery</span><strong>${t.delivery?money(t.delivery):'Free'}</strong></div><div class="summary-row"><span>Promo discount</span><strong>−${money(t.discount)}</strong></div><div class="summary-row"><span>Points discount</span><strong>−${money(t.pointsDiscount)}</strong></div><div class="summary-row total"><span>Total</span><strong>${money(t.total)}</strong></div><button class="primary-btn" onclick="openCheckout()">Checkout ${icon('arrow')}</button></div>`:`<div class="empty-state"><div class="empty-illustration">🛍️</div><h2>Your cart is empty</h2><p>Find a phone you love and it will appear here.</p><button class="primary-btn" onclick="setPage('shop')">Start Shopping</button></div>`}`;
}
function cartQty(key,d){const item=state.cart.find(i=>i.key===key);if(!item)return;item.qty+=d;if(item.qty<=0)state.cart=state.cart.filter(i=>i.key!==key);save();renderNav();renderCart()}
function removeCart(key){state.cart=state.cart.filter(i=>i.key!==key);save();renderNav();renderCart();toast('Item removed')}
function applyPromo(){const code=document.getElementById('promo').value.trim().toUpperCase();if(code==='RIDWAAN10'){state.promo=code;save();renderCart();toast('10% discount applied')}else{state.promo='';save();renderCart();toast('Promo code is not valid','!')}}

function openCheckout(){
  const t=cartTotals(),earned=state.cart.reduce((s,i)=>s+product(i.id).points*i.qty,0);
  openSheet(`<form id="checkoutForm" onsubmit="placeOrder(event)"><div class="sheet-head"><h2>Checkout</h2><button type="button" class="icon-btn close" onclick="closeSheet()" aria-label="Close checkout">${icon('x')}</button></div><div class="form-grid"><label class="field"><span>Full name *</span><input name="name" value="${safe(state.profile.name)}" autocomplete="name" required></label><label class="field"><span>Phone number *</span><input name="phone" value="${safe(state.profile.phone)}" type="tel" autocomplete="tel" placeholder="+252..." required></label><label class="field full"><span>Email *</span><input name="email" value="${safe(state.profile.email)}" type="email" autocomplete="email" required></label><label class="field full"><span>Delivery address *</span><textarea name="address" autocomplete="street-address" required>${safe(state.profile.address)}</textarea></label><label class="field full"><span>City *</span><input name="city" value="${safe(state.profile.city)}" required></label></div><div class="filter-group"><label>Payment method *</label><div class="payment-options">${['Cash on Delivery','Zaad','eDahab','Credit/Debit Card'].map((p,i)=>`<button type="button" class="payment-option ${i===0?'selected':''}" data-payment="${p}" onclick="choosePayment(this)"><span>${['💵','📲','💳','🏦'][i]}</span>${p}</button>`).join('')}</div><input type="hidden" name="payment" value="Cash on Delivery"></div><div class="summary-card"><div class="summary-row"><span>${state.cart.reduce((s,i)=>s+i.qty,0)} item(s)</span><strong>${money(t.subtotal)}</strong></div><div class="summary-row"><span>You will earn</span><strong>+${earned} points</strong></div><div class="summary-row total"><span>Total</span><strong>${money(t.total)}</strong></div></div><p class="error-text" id="checkoutError"></p><button class="primary-btn" type="submit">Place Order · ${money(t.total)}</button><p style="font-size:8px;color:var(--muted);text-align:center">Demo only — no real payment will be processed.</p></form>`);
}
function choosePayment(el){el.parentElement.querySelectorAll('.payment-option').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');document.querySelector('[name=payment]').value=el.dataset.payment}
function placeOrder(e){
  e.preventDefault();const form=e.target;if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));if(!data.name.trim()||!data.phone.trim()||!data.address.trim()||!data.city.trim()){document.getElementById('checkoutError').textContent='Please complete all required fields.';return}
  const t=cartTotals(),earned=state.cart.reduce((s,i)=>s+product(i.id).points*i.qty,0),spent=state.usePoints?Math.round(t.pointsDiscount*100):0;const number=`RMS-${Math.floor(100000+Math.random()*900000)}`;
  const order={number,date:new Date().toISOString(),customer:data.name,total:t.total,earned,items:state.cart.map(x=>({...x})),payment:data.payment};state.orders.unshift(order);state.points=Math.max(0,state.points-spent)+earned;state.profile={...state.profile,name:data.name,email:data.email,phone:data.phone,address:data.address,city:data.city};state.cart=[];state.promo='';state.usePoints=false;save();renderNav();
  openSuccess(order);
}
function openSuccess(order){modalRoot.innerHTML=`<div class="sheet success-sheet" role="dialog" aria-modal="true"><div class="grabber"></div><div class="success-badge">✓</div><h2>Order confirmed!</h2><p>Thanks, ${safe(order.customer)}. Your new phone journey starts now.</p><div class="success-data"><div class="summary-row"><span>Order number</span><strong>${order.number}</strong></div><div class="summary-row"><span>Total paid</span><strong>${money(order.total)}</strong></div><div class="summary-row"><span>Reward points earned</span><strong>+${order.earned}</strong></div></div><button class="primary-btn" onclick="closeSheet();setPage('home');confetti()">Continue Shopping</button></div>`;confetti()}

function membership(){if(state.points>=3000)return 'Platinum';if(state.points>=1800)return 'Gold';if(state.points>=1000)return 'Silver';return 'Bronze'}
function renderRewards(){
  const level=membership(),next=level==='Bronze'?1000:level==='Silver'?1800:level==='Gold'?3000:state.points;const floor=level==='Bronze'?0:level==='Silver'?1000:level==='Gold'?1800:3000;const pct=level==='Platinum'?100:Math.min(100,((state.points-floor)/(next-floor))*100);const dash=326-(326*pct/100);
  app.innerHTML=`${header('Rewards',`<button class="icon-btn" onclick="showRewardInfo()" aria-label="Rewards information">?</button>`)}<section class="rewards-hero"><p class="rewards-label">YOUR ${level.toUpperCase()} BALANCE</p><div class="progress-ring"><svg viewBox="0 0 120 120"><circle class="track" cx="60" cy="60" r="52"></circle><circle class="value" cx="60" cy="60" r="52" style="stroke-dashoffset:${dash}"></circle></svg><div class="ring-copy"><strong id="pointsCounter">0</strong><span>reward points</span></div></div><div class="level-progress-text">${level==='Platinum'?'You reached our highest level!':`${(next-state.points).toLocaleString()} points to ${level==='Gold'?'Platinum':level==='Silver'?'Gold':'Silver'}`}</div><div class="reward-actions"><button class="small-action" onclick="showOrders()">${icon('shop')}Purchases</button><button class="small-action" onclick="showPoints()">${icon('star')}Points</button><button class="small-action" onclick="showLevels()">${icon('arrow')}Level Up</button><button class="small-action" onclick="redeemPoints()">${icon('gift')}Redeem</button></div></section><div class="section-head"><h2>Membership levels</h2><button class="text-btn" onclick="showLevels()">How it works</button></div><div class="levels">${[['Bronze','🥉',0,999],['Silver','🥈',1000,1799],['Gold','🏆',1800,2999],['Platinum','💎',3000,5000]].map(([n,ic,min,max])=>{const fill=state.points<min?0:state.points>=max?100:((state.points-min)/(max-min))*100;return `<button class="level-card ${level===n?'current':''}" onclick="levelClick('${n}')"><div class="level-top"><span><b>${n}</b><p>${min.toLocaleString()}${n==='Platinum'?'+' : '–'+max.toLocaleString()} points</p></span><span class="level-icon">${ic}</span></div><div class="tiny-progress"><i style="width:${fill}%"></i></div></button>`}).join('')}</div><div class="section-head"><h2>Your Gold benefits</h2></div><div class="benefit-list"><div class="benefit"><span class="benefit-icon">🚚</span><span><b>Free priority delivery</b><span>On every eligible phone order</span></span></div><div class="benefit"><span class="benefit-icon">✦</span><span><b>2× reward points</b><span>Earn faster on selected products</span></span></div><div class="benefit"><span class="benefit-icon">🎁</span><span><b>Exclusive member offers</b><span>Early access to special prices</span></span></div></div><div class="section-head"><h2>Recent activity</h2><button class="text-btn" onclick="showPoints()">See all</button></div><div class="activity-list">${rewardActivity()}</div>`;
  animateCounter(state.points);if(level==='Gold'&&!goldShown){goldShown=true;setTimeout(showGold,700)}
}
function rewardActivity(){const acts=state.orders.slice(0,2).map(o=>`<div class="activity"><span class="activity-icon">📱</span><span><b>Order ${o.number}</b><span>${new Date(o.date).toLocaleDateString()}</span></span><strong class="activity-points">+${o.earned}</strong></div>`);acts.push(`<div class="activity"><span class="activity-icon">⭐</span><span><b>Welcome Gold bonus</b><span>Membership reward</span></span><strong class="activity-points">+150</strong></div>`,`<div class="activity"><span class="activity-icon">🎟️</span><span><b>Delivery reward used</b><span>Recent redemption</span></span><strong class="activity-points spend">−50</strong></div>`);return acts.join('')}
function animateCounter(end){const el=document.getElementById('pointsCounter');if(!el)return;const start=performance.now(),duration=1200;function step(t){const p=Math.min(1,(t-start)/duration);el.textContent=Math.floor(end*(1-Math.pow(1-p,3))).toLocaleString();if(p<1)requestAnimationFrame(step)}requestAnimationFrame(step)}
function levelClick(n){if(n==='Gold')showGold();else toast(`${n} level ${membership()===n?'is your current tier':'details opened'}`)}
function showGold(){openSheet(`<div class="gold-sheet"><div class="sheet-head"><span></span><button class="icon-btn close" onclick="closeSheet()" aria-label="Close">${icon('x')}</button></div><div class="trophy">🏆</div><h2>You’re Gold</h2><p>Congratulations, ${safe(state.profile.name)}! Your loyalty unlocked a more rewarding shopping experience.</p><div class="gold-benefits"><div class="gold-benefit"><span>🚚</span>Free delivery</div><div class="gold-benefit"><span>✦</span>2× points</div><div class="gold-benefit"><span>🎁</span>Member deals</div></div><button class="primary-btn" onclick="closeSheet();toast('Your Gold rewards are active')">View My Rewards</button></div>`);confetti()}
function showRewardInfo(){infoSheet('How rewards work','Earn points whenever you buy a phone. Every 100 points can save $1 at checkout. Your membership level updates automatically.')}
function showPoints(){openSheet(`<div class="sheet-head"><h2>Points activity</h2><button class="icon-btn close" onclick="closeSheet()">${icon('x')}</button></div><div class="activity-list">${rewardActivity()}</div>`)}
function showLevels(){infoSheet('Membership levels','Bronze starts at 0 points, Silver at 1,000, Gold at 1,800 and Platinum at 3,000. Higher levels unlock faster points and premium benefits.')}
function redeemPoints(){if(state.points<100)return toast('You need at least 100 points','!');infoSheet('Redeem points',`You have ${state.points.toLocaleString()} points, worth up to ${money(state.points/100)}. Turn on “Use reward points” in your cart to redeem them.`)}

function renderProfile(){
  app.innerHTML=`${header('Settings')}<section class="profile-card"><div class="avatar">R</div><div><h2>${safe(state.profile.name)}</h2><p>${safe(state.profile.email)}</p></div><button onclick="editProfile()">Edit</button></section><div class="settings-section"><p class="section-label">My account</p><div class="settings-card">${settingRow('shop','Order history',`${state.orders.length} completed orders`,'showOrders()')}${settingRow('heart','Wishlist',`${state.wishlist.length} saved phones`,'showWishlist()')}${settingRow('home','Saved addresses',state.profile.address?'1 saved address':'No saved address','editAddress()')}${settingRow('cart','Payment methods','Cash, Zaad, eDahab & cards','showPayments()')}</div></div><div class="settings-section"><p class="section-label">Preferences</p><div class="settings-card">${toggleRow('bell','Push notifications','Order and offer updates','notifications')}${toggleRow('user','Biometric lock','Visual demo setting','biometric')}${toggleRow('sun','Dark mode','Warm midnight appearance','theme')}<label class="settings-row"><span class="settings-icon">🌐</span><span class="settings-copy"><b>Language</b><span>App display language</span></span><select class="language-select" onchange="state.language=this.value;save();toast('Language preference saved')"><option ${state.language==='English'?'selected':''}>English</option><option ${state.language==='Somali'?'selected':''}>Somali</option><option ${state.language==='Arabic'?'selected':''}>Arabic</option></select></label></div></div><div class="settings-section"><p class="section-label">Support</p><div class="settings-card">${settingRow('gift','Help and support','FAQs and contact options','showHelp()')}${settingRow('user','About this app','Version 1.0.0','showAbout()')}<button class="settings-row logout" onclick="logoutDemo()"><span class="settings-icon">↪</span><span class="settings-copy"><b>Log out</b><span>Reset this local demo session</span></span>${icon('chevron','chev')}</button></div></div>`;
}
function settingRow(ic,title,sub,fn){return `<button class="settings-row" onclick="${fn}"><span class="settings-icon">${icon(ic)}</span><span class="settings-copy"><b>${title}</b><span>${sub}</span></span>${icon('chevron','chev')}</button>`}
function toggleRow(ic,title,sub,key){const on=key==='theme'?state.theme==='dark':state[key];return `<button class="settings-row" onclick="toggleSetting('${key}')"><span class="settings-icon">${icon(ic)}</span><span class="settings-copy"><b>${title}</b><span>${sub}</span></span><span class="toggle ${on?'on':''}" role="switch" aria-checked="${on}"><i></i></span></button>`}
function toggleSetting(key){if(key==='theme')state.theme=state.theme==='dark'?'light':'dark';else state[key]=!state[key];save();renderProfile();toast(key==='theme'?`${state.theme==='dark'?'Dark':'Light'} mode enabled`:'Setting updated')}
function editProfile(){openSheet(`<form onsubmit="saveProfile(event)"><div class="sheet-head"><h2>Edit profile</h2><button type="button" class="icon-btn close" onclick="closeSheet()">${icon('x')}</button></div><div class="form-grid"><label class="field full"><span>Full name</span><input name="name" value="${safe(state.profile.name)}" required></label><label class="field full"><span>Email</span><input name="email" type="email" value="${safe(state.profile.email)}" required></label><label class="field full"><span>Phone</span><input name="phone" type="tel" value="${safe(state.profile.phone)}"></label></div><button class="primary-btn" style="margin-top:16px">Save Profile</button></form>`)}
function saveProfile(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.profile={...state.profile,...d};save();closeSheet();renderProfile();toast('Profile updated')}
function editAddress(){openSheet(`<form onsubmit="saveAddress(event)"><div class="sheet-head"><h2>Saved address</h2><button type="button" class="icon-btn close" onclick="closeSheet()">${icon('x')}</button></div><div class="form-grid"><label class="field full"><span>Delivery address</span><textarea name="address" required>${safe(state.profile.address)}</textarea></label><label class="field full"><span>City</span><input name="city" value="${safe(state.profile.city)}" required></label></div><button class="primary-btn" style="margin-top:16px">Save Address</button></form>`)}
function saveAddress(e){e.preventDefault();Object.assign(state.profile,Object.fromEntries(new FormData(e.target)));save();closeSheet();renderProfile();toast('Address saved')}
function showOrders(){openSheet(`<div class="sheet-head"><h2>Order history</h2><button class="icon-btn close" onclick="closeSheet()">${icon('x')}</button></div>${state.orders.length?`<div class="activity-list">${state.orders.map(o=>`<div class="activity"><span class="activity-icon">📦</span><span><b>${o.number}</b><span>${new Date(o.date).toLocaleDateString()} · ${o.items.reduce((s,i)=>s+i.qty,0)} item(s)</span></span><strong>${money(o.total)}</strong></div>`).join('')}</div>`:`<div class="empty-state"><div class="empty-illustration">📦</div><h2>No orders yet</h2><p>Your completed orders will appear here.</p><button class="primary-btn" onclick="closeSheet();setPage('shop')">Explore Phones</button></div>`}`)}
function showWishlist(){const list=PRODUCTS.filter(p=>state.wishlist.includes(p.id));openSheet(`<div class="sheet-head"><h2>Wishlist</h2><button class="icon-btn close" onclick="closeSheet()">${icon('x')}</button></div>${list.length?`<div class="product-grid">${list.map(productCard).join('')}</div>`:`<div class="empty-state"><div class="empty-illustration">♡</div><h2>Nothing saved yet</h2><p>Tap the heart on any phone to save it.</p></div>`}`)}
function showPayments(){infoSheet('Payment methods','At checkout you can choose Cash on Delivery, Zaad, eDahab, or Credit/Debit Card. This front-end demo never processes real payments.')}
function showHelp(){openSheet(`<div class="sheet-head"><h2>Help & support</h2><button class="icon-btn close" onclick="closeSheet()">${icon('x')}</button></div><div class="benefit-list"><button class="benefit" onclick="infoSheet('Delivery information','Orders in Hargeisa normally arrive the same day. Other locations are shown as a demonstration only.')"><span class="benefit-icon">🚚</span><span><b>Delivery information</b><span>Times, fees and locations</span></span></button><button class="benefit" onclick="infoSheet('Returns','Demo orders can be reviewed in Order History. No real purchase is created.')"><span class="benefit-icon">↩</span><span><b>Returns & refunds</b><span>Learn about the demo policy</span></span></button><button class="benefit" onclick="toast('Support request drafted')"><span class="benefit-icon">💬</span><span><b>Contact support</b><span>Get help with your order</span></span></button></div>`)}
function showAbout(){infoSheet('Ridwaan Mobile Store','A premium mobile shopping demo designed and built with HTML5, CSS3 and vanilla JavaScript. Version 1.0.0.')}
function logoutDemo(){openSheet(`<div class="sheet-head"><h2>Log out?</h2><button class="icon-btn close" onclick="closeSheet()">${icon('x')}</button></div><p style="color:var(--muted);font-size:12px">This resets cart, wishlist, orders and preferences stored on this device.</p><div class="sheet-actions"><button class="secondary-btn" onclick="closeSheet()">Cancel</button><button class="primary-btn" onclick="confirmLogout()">Reset Demo</button></div>`)}
function confirmLogout(){localStorage.removeItem('rms_state');Object.assign(state,JSON.parse(JSON.stringify(DEFAULTS)));closeSheet();save();setPage('home');toast('Demo session reset')}

function infoSheet(title,text){openSheet(`<div class="sheet-head"><h2>${safe(title)}</h2><button class="icon-btn close" onclick="closeSheet()">${icon('x')}</button></div><p style="color:var(--muted);font-size:12px;line-height:1.7">${safe(text)}</p><button class="primary-btn" onclick="closeSheet()">Got it</button>`)}
function openSheet(content){modalRoot.innerHTML=`<div class="sheet" role="dialog" aria-modal="true"><div class="grabber"></div>${content}</div>`;modalRoot.onclick=e=>{if(e.target===modalRoot)closeSheet()};setTimeout(()=>modalRoot.querySelector('button,input')?.focus(),100)}
function closeSheet(){modalRoot.innerHTML='';modalRoot.onclick=null}
function toast(message,mark='✓'){const el=document.createElement('div');el.className='toast';el.innerHTML=`<i>${mark}</i><span>${safe(message)}</span>`;document.getElementById('toastRegion').appendChild(el);setTimeout(()=>{el.style.opacity='0';el.style.transform='translateY(-10px)';setTimeout(()=>el.remove(),250)},2300)}
function confetti(){const colors=['#f2b72b','#db4f16','#ffdf83','#8b3512'];for(let i=0;i<24;i++){const s=document.createElement('i');s.style.cssText=`position:fixed;z-index:90;left:${45+Math.random()*10}%;top:42%;width:${4+Math.random()*5}px;height:${6+Math.random()*7}px;background:${colors[i%colors.length]};border-radius:2px;pointer-events:none;transition:transform 1.1s cubic-bezier(.2,.7,.3,1),opacity 1.1s`;document.body.appendChild(s);requestAnimationFrame(()=>{s.style.transform=`translate(${(Math.random()-.5)*340}px,${Math.random()*420-210}px) rotate(${Math.random()*600}deg)`;s.style.opacity='0'});setTimeout(()=>s.remove(),1200)}}

init();
